language: node_js
node_js: 12

stages:
  - test
  - deploy

jobs:
  include:

    - stage: test
      services:
        - mongodb
      env:
        - JARDI_TEST_MONGO_URI="mongodb://127.0.0.1:27017/test-jardin?retryWrites=true&w=majority" JARDI_TEST_ADMIN_MONGO_DB_NAME=test-jardinAdmin
      script: npm run cover

    - stage: deploy
      if: (tag =~ ^v)
      script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_DEPLOY_TOKEN}" > .npmrc
        - npm whoami # rely on .npmrc
        - npm publish
      on:
        tags: true
        branch: master

