language: node_js
node_js: 12

stages:
  - test
  - deploy

jobs:
  include:

    - stage: test
      services:
        - mongodb
      env:
        - JARDI_MONGO_URI="mongodb://127.0.0.1:27017/jardin?retryWrites=true&w=majority" JARDI_ADMIN_MONGO_DB_NAME=jardinAdmin
      script: npm test

    - stage: deploy
      if: (tag =~ ^v) AND (branch =  master)
      script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_DEPLOY_TOKEN}" > .npmrc
        - npm whoami # rely on .npmrc
        - npm publish
      on:
        tags: true
        branch: master

